### ISSUE TITLE
Expecting no alpha in the result when casting a color with alpha to rgb

### ISSUE THREAD

**Issue by archmoj** [dfcreative/color-parse#1]
Currently casting/parsing `rgb`(255, 255, 255, 0.9) has a result identical to `rgba`(255, 255, 255, 0.9); whereas it is expected to have alpha equal 1 in the result.
@dy would you be interested in receiving a PR to possibly help fix this issue?
Thank you.

cc: @etpinard

**Comment by dy** [comment]
I see. Well, the input is invalid anyways, so there's no guarantee of correctness of the output.

I'd rather look at color validation, possibly package. Eg. `is-color` or `is-valid-color`. I had use-cases for that already too. I'd gladly accept that to @colorjs if you like @archmoj.
Although, there's already one https://www.npmjs.com/package/is-color.

If you want to have that single case fixed, sure.

**Comment by archmoj** [comment]
Thanks very much @dy.
Yes only that single case is enough.
So I move forward and open a PR.
Best regards.
