### ISSUE TITLE
Not working as an ESM module after ugrading to v2 - Cannot use import statement outside a module

### ISSUE THREAD

**Issue by tommymetz** [dfcreative/color-parse#11]
After upgrading from `color-rgba` v2 to v3 (where `color-parse` upgraded from v1 to v2) we are getting the following module error:

```
 Details:

    /home/circleci/project/node_modules/color-rgba/index.js:2
    import parse from 'color-parse'
    ^^^^^^

    SyntaxError: Cannot use import statement outside a module

    > 11 | import rgba from 'color-rgba'
```

This worked as an ESM module on the old version.

Great package! Thanks for your help in advance!

**Comment by dy** [comment]
Hi @tommymetz! Likely you are using commonjs style of imports - I suggest you keep color-parse v2 or upgrade your code to ES modules.
