### ISSUE TITLE
Invalid Podfile [ERR_PACKAGE_PATH_NOT_EXPORTED]

### ISSUE THREAD

**Issue by BradleyGyemi-Qlik** [dfcreative/color-parse#4]
`Invalid Podfile file: 859: unexpected token at 'Error [ERR_PACKAGE_PATH_NOT_EXPORTED]: Package subpath './package.json' is not defined by "exports" in /usr/app/node_modules/color-parse/package.json`

This error occurs when I run `pod install` in a react-native project with:
react-native: 0.69
node: 17.8.0
react: 17.0.2

**Comment by aidan-24com** [comment]
@BradleyGyemi-Qlik  
update `@react-native-community/cli` to >= 8.0.4. https://github.com/react-native-community/cli/issues/1650

Also make sure `./node_modules/react-native/package.json` is using `^8.0.[X]` for `@react-native-community/cli`


Alternatively, use `@react-native-community/cli` at `'7'`
