### ISSUE TITLE
Use case-insensitive CSS strings 

### ISSUE THREAD

**Issue by 28raining** [dfcreative/color-parse#5]
All the colors exported from color-name are lower case

but CSS keywords are supposed to be case insensitive
https://drafts.csswg.org/css-color/#named-colors

`parse('blue')` works but `parse('BLUE')` doesn't work

**Comment by 28raining** [comment]
Created pull request
https://github.com/colorjs/color-parse/pull/6

**Comment by dy** [comment]
Fixed by #6
