### ISSUE TITLE
Add type declarations

### ISSUE THREAD

**Issue by avivnakar** [dfcreative/color-parse#9]
since the api is pretty simple, adding a d.ts file can help typescript users if the authors are not interested in re-writing the package in ts. even creating a definitely-typed package can help

```ts
export default function parse(cstr:string): {

alpha: number;
values:[number, number, number];
space:'rgb'|'hsl';
}
```
That is just a simple example that can help fellow Devs to use the library and won't require a full rewrite

**Comment by dy** [comment]
For sure! I'd appreciate your contribution

**Comment by dy** [comment]
Done
